package jinyou.model;

// Generated 2014-10-13 10:39:52 by Hibernate Tools 3.2.2.GA

/**
 * Aera generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private int AId;
	private Double ALattop;
	private Double ALongtop;
	private Double ALatright;
	private Double ALongright;
	private Double ALatleft;
	private Double ALongleft;
	private Double ALatbottom;
	private Double ALongbottom;

	public Area() {
	}

	public Area(int AId) {
		this.AId = AId;
	}

	public Area(int AId, Double ALattop, Double ALongtop, Double ALatright,
			Double ALongright, Double ALatleft, Double ALongleft, Double ALatbottom,
			Double ALongbottom) {
		this.AId = AId;
		this.ALattop = ALattop;
		this.ALongtop = ALongtop;
		this.ALatright = ALatright;
		this.ALongright = ALongright;
		this.ALatleft = ALatleft;
		this.ALongleft = ALongleft;
		this.ALatbottom = ALatbottom;
		this.ALongbottom = ALongbottom;
	}

	public int getAId() {
		return this.AId;
	}

	public void setAId(int AId) {
		this.AId = AId;
	}

	public Double getALattop() {
		return this.ALattop;
	}

	public void setALattop(Double ALattop) {
		this.ALattop = ALattop;
	}

	public Double getALongtop() {
		return this.ALongtop;
	}

	public void setALongtop(Double ALongtop) {
		this.ALongtop = ALongtop;
	}

	public Double getALatright() {
		return this.ALatright;
	}

	public void setALatright(Double ALatright) {
		this.ALatright = ALatright;
	}

	public Double getALongright() {
		return this.ALongright;
	}

	public void setALongright(Double ALongright) {
		this.ALongright = ALongright;
	}

	public Double getALatleft() {
		return this.ALatleft;
	}

	public void setALatleft(Double ALatleft) {
		this.ALatleft = ALatleft;
	}

	public Double getALongleft() {
		return this.ALongleft;
	}

	public void setALongleft(Double ALongleft) {
		this.ALongleft = ALongleft;
	}

	public Double getALatbottom() {
		return this.ALatbottom;
	}

	public void setALatbottom(Double ALatbottom) {
		this.ALatbottom = ALatbottom;
	}

	public Double getALongbottom() {
		return this.ALongbottom;
	}

	public void setALongbottom(Double ALongbottom) {
		this.ALongbottom = ALongbottom;
	}

}
