package jinyou.model;

// Generated 2014-10-13 10:39:52 by Hibernate Tools 3.2.2.GA

/**
 * Btype generated by hbm2java
 */
public class Btype implements java.io.Serializable {

	private int btType;
	private String btString;
	private String btStay;

	public Btype() {
	}

	public Btype(int btType) {
		this.btType = btType;
	}

	public Btype(int btType, String btString, String btStay) {
		this.btType = btType;
		this.btString = btString;
		this.btStay = btStay;
	}

	public int getBtType() {
		return this.btType;
	}

	public void setBtType(int btType) {
		this.btType = btType;
	}

	public String getBtString() {
		return this.btString;
	}

	public void setBtString(String btString) {
		this.btString = btString;
	}

	public String getBtStay() {
		return this.btStay;
	}

	public void setBtStay(String btStay) {
		this.btStay = btStay;
	}

}
