package jinyou.model;

// default package
// Generated 2014-10-15 16:41:35 by Hibernate Tools 3.2.2.GA



/**
 * Business generated by hbm2java
 */
public class Business implements java.io.Serializable {

	private int BSalerid;
	private String BSalername;
	private Integer BSalertype;
	private String BUrl;
	private String BDetail;
	private Integer BUsergrade;
	private Double BLat;
	private Double BLog;
	private String BTel;
	private String BAccount;
	private Integer BUsercredit;

	public Business() {
	}

	public Business(int BSalerid) {
		this.BSalerid = BSalerid;
	}

	public Business(int BSalerid, String BSalername, Integer BSalertype,
			String BUrl, String BDetail, Integer BUsergrade, Double BLat,
			Double BLog, String BTel, String BAccount, Integer BUsercredit) {
		this.BSalerid = BSalerid;
		this.BSalername = BSalername;
		this.BSalertype = BSalertype;
		this.BUrl = BUrl;
		this.BDetail = BDetail;
		this.BUsergrade = BUsergrade;
		this.BLat = BLat;
		this.BLog = BLog;
		this.BTel = BTel;
		this.BAccount = BAccount;
		this.BUsercredit = BUsercredit;
	}

	public int getBSalerid() {
		return this.BSalerid;
	}

	public void setBSalerid(int BSalerid) {
		this.BSalerid = BSalerid;
	}

	public String getBSalername() {
		return this.BSalername;
	}

	public void setBSalername(String BSalername) {
		this.BSalername = BSalername;
	}

	public Integer getBSalertype() {
		return this.BSalertype;
	}

	public void setBSalertype(Integer BSalertype) {
		this.BSalertype = BSalertype;
	}

	public String getBUrl() {
		return this.BUrl;
	}

	public void setBUrl(String BUrl) {
		this.BUrl = BUrl;
	}

	public String getBDetail() {
		return this.BDetail;
	}

	public void setBDetail(String BDetail) {
		this.BDetail = BDetail;
	}

	public Integer getBUsergrade() {
		return this.BUsergrade;
	}

	public void setBUsergrade(Integer BUsergrade) {
		this.BUsergrade = BUsergrade;
	}

	public Double getBLat() {
		return this.BLat;
	}

	public void setBLat(Double BLat) {
		this.BLat = BLat;
	}

	public Double getBLog() {
		return this.BLog;
	}

	public void setBLog(Double BLog) {
		this.BLog = BLog;
	}

	public String getBTel() {
		return this.BTel;
	}

	public void setBTel(String BTel) {
		this.BTel = BTel;
	}

	public String getBAccount() {
		return this.BAccount;
	}

	public void setBAccount(String BAccount) {
		this.BAccount = BAccount;
	}

	public Integer getBUsercredit() {
		return this.BUsercredit;
	}

	public void setBUsercredit(Integer BUsercredit) {
		this.BUsercredit = BUsercredit;
	}

}
