package jinyou.model;

// Generated 2014-10-13 10:39:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String CUsername;
	private Integer CUserid;
	private String CAlias;
	private String CPassword;
	private Integer CUsertype;
	private String CAddr;
	private String CUrl;
	private Date CCreatetime;
	private Integer CUsergrade;
	private Integer CUsercredit;
	private Double CLat;
	private Double CLong;
	private Integer CCapturearea;

	public Customer() {
	}

	public Customer(String CUsername) {
		this.CUsername = CUsername;
	}

	public Customer(String CUsername, Integer CUserid, String CAlias,
			String CPassword, Integer CUsertype, String CAddr, String CUrl,
			Date CCreatetime, Integer CUsergrade, Integer CUsercredit,
			Double CLat, Double CLong, Integer CCapturearea) {
		this.CUsername = CUsername;
		this.CUserid = CUserid;
		this.CAlias = CAlias;
		this.CPassword = CPassword;
		this.CUsertype = CUsertype;
		this.CAddr = CAddr;
		this.CUrl = CUrl;
		this.CCreatetime = CCreatetime;
		this.CUsergrade = CUsergrade;
		this.CUsercredit = CUsercredit;
		this.CLat = CLat;
		this.CLong = CLong;
		this.CCapturearea = CCapturearea;
	}

	public String getCUsername() {
		return this.CUsername;
	}

	public void setCUsername(String CUsername) {
		this.CUsername = CUsername;
	}

	public Integer getCUserid() {
		return this.CUserid;
	}

	public void setCUserid(Integer CUserid) {
		this.CUserid = CUserid;
	}

	public String getCAlias() {
		return this.CAlias;
	}

	public void setCAlias(String CAlias) {
		this.CAlias = CAlias;
	}

	public String getCPassword() {
		return this.CPassword;
	}

	public void setCPassword(String CPassword) {
		this.CPassword = CPassword;
	}

	public Integer getCUsertype() {
		return this.CUsertype;
	}

	public void setCUsertype(Integer CUsertype) {
		this.CUsertype = CUsertype;
	}

	public String getCAddr() {
		return this.CAddr;
	}

	public void setCAddr(String CAddr) {
		this.CAddr = CAddr;
	}

	public String getCUrl() {
		return this.CUrl;
	}

	public void setCUrl(String CUrl) {
		this.CUrl = CUrl;
	}

	public Date getCCreatetime() {
		return this.CCreatetime;
	}

	public void setCCreatetime(Date CCreatetime) {
		this.CCreatetime = CCreatetime;
	}

	public Integer getCUsergrade() {
		return this.CUsergrade;
	}

	public void setCUsergrade(Integer CUsergrade) {
		this.CUsergrade = CUsergrade;
	}

	public Integer getCUsercredit() {
		return this.CUsercredit;
	}

	public void setCUsercredit(Integer CUsercredit) {
		this.CUsercredit = CUsercredit;
	}

	public Double getCLat() {
		return this.CLat;
	}

	public void setCLat(Double CLat) {
		this.CLat = CLat;
	}

	public Double getCLong() {
		return this.CLong;
	}

	public void setCLong(Double CLong) {
		this.CLong = CLong;
	}

	public Integer getCCapturearea() {
		return this.CCapturearea;
	}

	public void setCCapturearea(Integer CCapturearea) {
		this.CCapturearea = CCapturearea;
	}

}
