package jinyou.model;

// Generated 2014-10-13 10:39:52 by Hibernate Tools 3.2.2.GA

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int OId;
	private Integer OOrderid;
	private Integer ODelivery;
	private Integer OStatus;

	public Orders() {
	}

	public Orders(int OId) {
		this.OId = OId;
	}

	public Orders(int OId, Integer OOrderid, Integer ODelivery, Integer OStatus) {
		this.OId = OId;
		this.OOrderid = OOrderid;
		this.ODelivery = ODelivery;
		this.OStatus = OStatus;
	}

	public int getOId() {
		return this.OId;
	}

	public void setOId(int OId) {
		this.OId = OId;
	}

	public Integer getOOrderid() {
		return this.OOrderid;
	}

	public void setOOrderid(Integer OOrderid) {
		this.OOrderid = OOrderid;
	}

	public Integer getODelivery() {
		return this.ODelivery;
	}

	public void setODelivery(Integer ODelivery) {
		this.ODelivery = ODelivery;
	}

	public Integer getOStatus() {
		return this.OStatus;
	}

	public void setOStatus(Integer OStatus) {
		this.OStatus = OStatus;
	}

}
