package jinyou.model;

// Generated 2014-10-16 10:09:58 by Hibernate Tools 3.2.2.GA

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int PProductid;
	private Integer BSalerid;
	private String PProductname;
	private Integer PProducttype;
	private String PUrl;
	private String PDetail;
	private Float PPrice;
	private Integer PLeftcnt;

	public Product() {
	}

	public Product(int PProductid ) {
		this.PProductid = PProductid;
	}
	
	
	
	public Product(int PProductid,String PDetail){
		this.PProductid=PProductid;
		this.PDetail=PDetail;
	}

	public Product(int PProductid, Integer BSalerid, String PProductname,
			Integer PProducttype, String PUrl, String PDetail, Float PPrice,
			Integer PLeftcnt) {
		this.PProductid = PProductid;
		this.BSalerid = BSalerid;
		this.PProductname = PProductname;
		this.PProducttype = PProducttype;
		this.PUrl = PUrl;
		this.PDetail = PDetail;
		this.PPrice = PPrice;
		this.PLeftcnt = PLeftcnt;
	}

	public int getPProductid() {
		return this.PProductid;
	}

	public void setPProductid(int PProductid) {
		this.PProductid = PProductid;
	}

	public Integer getBSalerid() {
		return this.BSalerid;
	}

	public void setBSalerid(Integer BSalerid) {
		this.BSalerid = BSalerid;
	}

	public String getPProductname() {
		return this.PProductname;
	}

	public void setPProductname(String PProductname) {
		this.PProductname = PProductname;
	}

	public Integer getPProducttype() {
		return this.PProducttype;
	}

	public void setPProducttype(Integer PProducttype) {
		this.PProducttype = PProducttype;
	}

	public String getPUrl() {
		return this.PUrl;
	}

	public void setPUrl(String PUrl) {
		this.PUrl = PUrl;
	}

	public String getPDetail() {
		return this.PDetail;
	}

	public void setPDetail(String PDetail) {
		this.PDetail = PDetail;
	}

	public Float getPPrice() {
		return this.PPrice;
	}

	public void setPPrice(Float PPrice) {
		this.PPrice = PPrice;
	}

	public Integer getPLeftcnt() {
		return this.PLeftcnt;
	}

	public void setPLeftcnt(Integer PLeftcnt) {
		this.PLeftcnt = PLeftcnt;
	}

}
